fix: prevent error in attic from failing the entire workflow

diff --git a/.github/workflows/review.yml b/.github/workflows/review.yml
--- a/.github/workflows/review.yml
+++ b/.github/workflows/review.yml
@@ -156,7 +156,10 @@ jobs:
 
           if [[ ${{ vars.ATTIC_SERVER != '' && vars.ATTIC_CACHE != '' }} = true ]]; then
             attic login default "$ATTIC_SERVER" "$ATTIC_TOKEN"
-            attic cache info "$ATTIC_CACHE"
+            if ! attic cache info "$ATTIC_CACHE"; then
+              echo "::error:: attic returned an error"
+              exit 0
+            fi
             attic push --stdin "$ATTIC_CACHE" < paths
             info=$(curl -f -H "Authorization: Bearer ${ATTIC_TOKEN}" "${ATTIC_SERVER}_api/v1/cache-config/${ATTIC_CACHE}")
             substituter_endpoint=$(jq -r .substituter_endpoint <<< "$info")
